name: tdvp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # library package
  image_picker: ^0.8.6
  table_calendar: ^2.3.1
  localization: ^2.1.0
  avatar_view: ^1.0.1
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  carousel_pro: ^1.0.0
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.1.5

  intl: ^0.17.0
  datetime_picker_formfield: any
  date_time_picker: ^2.1.0
  provider: ^4.3.2
  http: ^0.13.0



  cached_network_image: ^3.2.0
  badges: ^2.0.2
  image_gallery_saver: '^1.7.1'
  flutter_local_notifications: ^13.0.0

  # chart
  flutter_charts: ^0.5.0
  syncfusion_flutter_charts: ^20.4.41  

  # firebase db
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.2


  # fix error
  firebase_messaging_platform_interface: any
  firebase_storage_platform_interface: any
  cloud_functions_platform_interface: any
  cloud_firestore_platform_interface: any
  firebase_auth_platform_interface: any
  firebase_database_platform_interface: any




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/board/
    - assets/images/icons/

  fonts:
    - family: THSarabunNew
      fonts:
        - asset: assets/fonts/THSarabunNew.ttf
        - asset: assets/fonts/THSarabunNew Bold.ttf
        - asset: assets/fonts/THSarabunNew BoldItalic.ttf
        - asset: assets/fonts/THSarabunNew Italic.ttf

    - family: Charmonman
      fonts:
        - asset: assets/fonts/Charmonman-Bold.ttf
        - asset: assets/fonts/Charmonman-Regular.ttf